seed: 2025

eval_env:
  make_env: True

  env_id: "PickSubtaskTrain-v0"
  num_envs: 189
  max_episode_steps: 200
 
  continuous_task: True

  cat_state: True
  cat_pixels: False
  frame_stack: 1

  stationary_base: False
  stationary_torso: False
  stationary_head: True

  task_plan_fp: /raid/wenbo/assets/maniskill/data/scene_datasets/replica_cad_dataset/rearrange/task_plans/set_table/pick/train/024_bowl.json
  spawn_data_fp: /raid/wenbo/assets/maniskill/data/scene_datasets/replica_cad_dataset/rearrange/spawn_data/set_table/pick/train/spawn_data.pt

  record_video: True
  info_on_video: True

  extra_stat_keys: []

  env_kwargs:
    robot_force_mult: 0.001
    robot_force_penalty_min: 0.2
    target_randomization: False

algo:
  name: bc

  lr: 3e-4
  batch_size: 512

  epochs: 100
  eval_freq: 2
  log_freq: 1
  save_freq: 1

  trajs_per_obj: 1000
  data_dir_fp: /raid/wenbo/project/mshab/mshab_exps/gen_data_save_trajectories/set_table/pick/train/024_bowl/20251015_091350.h5
  max_cache_size: 0

  save_backup_ckpts: False

  pi0_model:
      # action_dim: 7
      action_horizon: 1
      max_token_len: 180
      paligemma_variant: "gemma_2b_lora"        # <--- 修改这里
      action_expert_variant: "gemma_300m_lora"  # <--- 修改这里
      pi05: False

logger:
  workspace: mshab_exps
  exp_name: bc-settable-open-fridge
  clear_out: True
  
  tensorboard: False
  wandb: True
